### ISSUE TITLE
elm-app start not working out of the box

### ISSUE THREAD

**Issue by dkarter** [halfzebra/create-elm-app#108] opened 2017-03-26 08:01 UTC
I followed the steps in the readme, and out of the box `elm-app start` is not working.

```
[2J[3J[HCompilation failed.

Error in   TypeError: Cannot read property '0' of undefined
  
  - ExternalModuleFactoryPlugin.js:18 ExternalModuleFactoryPlugin.<anonymous>
    [global]/[webpack]/lib/ExternalModuleFactoryPlugin.js:18:38
  
  - NormalModuleFactory.js:159 
    [global]/[create-elm-app]/[webpack]/lib/NormalModuleFactory.js:159:3
  
  - Tapable.js:75 NormalModuleFactory.applyPluginsAsyncWaterfall
    [global]/[tapable]/lib/Tapable.js:75:69
  
  - NormalModuleFactory.js:144 NormalModuleFactory.create
    [global]/[create-elm-app]/[webpack]/lib/NormalModuleFactory.js:144:8
  
  - Compilation.js:356 Compilation.process [as _addModuleChain]
    [global]/[create-elm-app]/[webpack]/lib/Compilation.js:356:16
  
  - Compilation.js:424 Compilation.process [as addEntry]
    [global]/[create-elm-app]/[webpack]/lib/Compilation.js:424:7
  
  - SingleEntryPlugin.js:24 Compiler.compiler.plugin
    [global]/[webpack]/lib/SingleEntryPlugin.js:24:16
  
  - Tapable.js:107 Compiler.applyPluginsParallel
    [global]/[tapable]/lib/Tapable.js:107:14
  
  - Compiler.js:394 Compiler.compile
    [global]/[create-elm-app]/[webpack]/lib/Compiler.js:394:7
  
  - Compiler.js:203 Compiler.runAsChild
    [global]/[create-elm-app]/[webpack]/lib/Compiler.js:203:7
  
  - compiler.js:70 
    [global]/[html-webpack-plugin]/lib/compiler.js:70:19
  
  - debuggability.js:300 Promise._execute
    [global]/[bluebird]/js/release/debuggability.js:300:9
  
  - promise.js:481 Promise._resolveFromExecutor
    [global]/[bluebird]/js/release/promise.js:481:18
  
  - promise.js:77 new Promise
    [global]/[bluebird]/js/release/promise.js:77:14
  
  - compiler.js:69 Object.compileTemplate
    [global]/[html-webpack-plugin]/lib/compiler.js:69:10
  
  - index.js:47 Compiler.<anonymous>
    [global]/[html-webpack-plugin]/index.js:47:40
  


Error in ./src/index.js
Module not found: 'style' in /Users/dkarter/Dropbox/Developer/learning/elm/cli/src

 @ ./src/index.js 1:0-21

Error in ./src/index.js
Module not found: 'file' in /Users/dkarter/Dropbox/Developer/learning/elm/cli/src

 @ ./src/index.js 2:15-36

Error in ./src/index.js
Module not found: 'elm-hot' in /Users/dkarter/Dropbox/Developer/learning/elm/cli/src

 @ ./src/index.js 3:10-31

```

I haven't made any changes to any of the files, just a fresh new app.

**Comment by emilaasa** [comment] 2017-04-04 07:18
**Same here, following error message:**
```sh
Compilation failed.
Error in ./src/index.js
Module not found: 'style' in /home/ea/my-app/src
 @ ./src/index.js 1:0-21
Error in ./src/index.js
Module not found: 'file' in /home/ea/my-app/src
 @ ./src/index.js 2:15-36
Error in ./src/index.js
Module not found: 'elm-hot' in /home/ea/my-app/src
 @ ./src/index.js 3:10-31
```
**How to reproduce:**
```sh
npm install create-elm-app -g
create-elm-app my-app
cd my-app/
elm-app start
```

**Execution env:**
```sh
$ node -v
v6.9.5
$ uname -a
Linux 4.4.0-66-generic 87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by fobos** [comment] 2017-04-13 02:55
@dkarter @emilaasa what version of `create-elm-app` you use?
Can you show me structure of created app and content of the file logged in your err msessages `./src/index.js`

**Comment by emilaasa** [comment] 2017-04-13 07:31
```
  "name": "create-elm-app",
  "version": "0.3.2",
```
`src/index.js`:

```
require('./main.css');
var logoPath = require('./logo.svg');
var Elm = require('./Main.elm');

var root = document.getElementById('root');

Elm.Main.embed(root, logoPath);
```

**Comment by fobos** [comment] 2017-04-13 07:42
@emilaasa big thanx! Will investigate the trouble. But I recommend use latest version `v0.4.0` of the package. 

@halfzebra it would be great to release `v0.4.1` with latest fixes. What you think?

**Comment by fobos** [comment] 2017-04-13 16:46
I can't reproduce the issue.  

@emilaasa I see odd `tmp` dir in you structure. I suppose that something went wrong during installation elm pkgs or during webpack task.
Can you try latest version of the package?

**Comment by emilaasa** [comment] 2017-04-13 17:55
Ah yeah sorry for the tempfile, it's what I made the gist from! I'll use latest package and report back later this evening!

**Comment by dkarter** [comment] 2017-04-13 21:19
@fobos I was using v0.3.2 when reporting this bug.

Just installed latest version using yarn (which resolved to 0.5.0):

```
$ create-elm-app --version

Usage: create-elm-app <project-directory>

where <project-directory> is the name of the directory with your future project

Elm Platform 0.18.0

create-elm-app@0.5.0 /Users/user/.config/yarn/global/node_modules/create-elm-app
```

Now when I run `create-elm-app experiment`

I get:

```
Creating experiment project...


Failed to install elm packages

Please, make sure you have internet connection!

In case if you are running Unix OS, you might look in to this issue:

    https://github.com/halfzebra/create-elm-app/issues/10
```

I am on macOS 10.12.4

If I go into the directory and run `elm-app start`

I get in the browser:

```
Failed to compile.

Error in ./src/index.js
Module not found: Can't resolve 'style-loader' in '/Users/user/dev/learning/elm/experiment'

 @ multi /Users/user/.config/yarn/global/~/react-dev-utils/webpackHotDevClient.js (webpack)/hot/dev-server.js ./src/index
```

and in the CLI:

```
Compilation failed.

Error in ./src/index.js
Module not found: Can't resolve 'style-loader' in '/Users/user/dev/learning/elm/experiment'

 @ multi /Users/user/.config/yarn/global/~/react-dev-utils/webpackHotDevClient.js (webpack)/hot/dev-server.js ./src/index

Error in ./src/index.js
Module not found: Can't resolve 'file-loader' in '/Users/user/dev/learning/elm/experiment'

 @ multi /Users/user/.config/yarn/global/~/react-dev-utils/webpackHotDevClient.js (webpack)/hot/dev-server.js ./src/index

Error in ./src/index.js
Module not found: Can't resolve 'elm-hot-loader' in '/Users/user/dev/learning/elm/experiment'

 @ multi /Users/user/.config/yarn/global/~/react-dev-utils/webpackHotDevClient.js (webpack)/hot/dev-server.js ./src/index
```

**Comment by emilaasa** [comment] 2017-04-18 07:37
Works well now on 0.6.0!

**Comment by newswim** [comment] 2017-04-18 16:09
I've just installed 0.6.0 globally (using yarn), and get the following error after running `elm-app start`

```
Failed to compile.

Error in ./src/index.js
Module not found: Can't resolve 'style-loader' in '/Users/dm/dev/learnelm.com/app'

 @ multi /Users/dm/.config/yarn/global/~/react-dev-utils/webpackHotDevClient.js (webpack)/hot/dev-server.js ./src/index
```

**Comment by newswim** [comment] 2017-04-18 16:13
Works fine if I don't use yarn. Probably a difference in how the dependencies are installed.

**Comment by halfzebra** [comment] 2017-04-19 07:53
Closing that issue in favor of #102

**Closed by halfzebra** 2017-04-19 07:53 UTC
Labels: fix, pr / help wanted
