### ISSUE TITLE
elm-app build - UglifyJs undefined error

### ISSUE THREAD

**Issue by dipaliso** [halfzebra/create-elm-app#482] opened 2020-07-04 12:15 UTC
### Is this a bug report?

Yes

### Environment

1. `node -v`: v11.1.0
2. `npm -v`: 6.14.5
3. `yarn --version` (if you use Yarn): -
4. `npm ls create-elm-app -g` (if you haven’t ejected):

```
/usr/local/lib
└── create-elm-app@4.2.23
```

Then, specify:

1. Operating system: Mac OS 10.12.6
2. Browser and version (if relevant): -

### Steps to Reproduce

```
elm-app build

Creating an optimized production build...
Failed to compile.

static/js/vendors~main.3e881061.chunk.js from UglifyJs
undefined
```

### Reproducible Demo

https://github.com/girishso/multiplayer-cards

**Comment by Ernmodern** [comment] 2020-09-22 18:29
I am experiencing the same issue and I have tracked it down to Firebase v7+, in particular with the Firestore module. The Reproducible Demo is using Firebase "^7.15.1"

My current workaround is not to optimize the files on build. But obviously a fix would be better.

**Comment by jlengrand** [comment] 2020-09-27 11:49
I wonder if the issue is not exactly the same as another one I had on my repo. It surely looked exactly the same : https://github.com/jlengrand/elm-firebase/issues/10

**Comment by jlengrand** [comment] 2020-09-27 11:49
This is the PR that fixed the issue in the forementioned repo : https://github.com/jlengrand/elm-firebase/pull/11

**Comment by jlengrand** [comment] 2020-09-27 12:05
I can indeed validate that this is the issue (that it is not related to create-elm-app) and I have made a PR that fixes it on your repository @dipaliso .

You can thank @joshuanianji for the fix. 

Here is the PR : https://github.com/girishso/multiplayer-cards/pull/2.

Have a nice sunday all!

@halfzebra AFAIK, this can be closed, as it is not related to this repository :). Maybe @dipaliso can validate.

**Comment by Ernmodern** [comment] 2020-09-27 17:32
@jlengrand Thank you.

**Comment by halfzebra** [comment] 2020-09-28 07:25
@jlengrand Thanks for the update, Julien!

I'll close this issue 🙌

**Closed by halfzebra** 2020-09-28 07:25 UTC
