### ISSUE TITLE
asking path

### ISSUE THREAD

**Issue by keahmed68** [halfzebra/create-elm-app#228] opened 2018-02-03 01:52 UTC
installation was C:\>npm install create-elm-app -g
but there is issue in creating app
create-elm-app my-app
C:\Users\keahm\AppData\Roaming\npm\node_modules\create-elm-app\bin\create-elm-app-cli.js:5
const path = require('path');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

### Is this a bug report?

(write your answer here)

### Environment

1. `node -v`:
2. `npm -v`:
3. `yarn --version` (if you use Yarn):
4. `npm ls create-elm-app -g` (if you haven’t ejected):

Then, specify:

1. Operating system:
2. Browser and version (if relevant):

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Please add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

**Comment by halfzebra** [comment] 2018-02-05 10:33
@keahmed68 thanks for reporting a bug.

This issue typically occurs, when you are running an older version of Node, which does not support `const` statement.

In Create Elm App we officially support Node 6 LTS and above, so I would suggest running `node -v` to figure out which version you are running and upgrading it if it's lower than 6.

I'm closing this issue for now, but please feel free to reopen it if your issue is not caused by an unsupported Node version.

**Closed by halfzebra** 2018-02-05 10:33 UTC
