### ISSUE TITLE
elm-app test --watch fails with EADDRINUSE 

### ISSUE THREAD

**Issue by mandrolic** [halfzebra/create-elm-app#312] opened 2018-10-13 08:59 UTC
### Environment

1. `node -v`: 8.12.0
2. `npm -v`: 6.4.1
3. `yarn --version` (if you use Yarn):
4. `npm ls create-elm-app -g` (if you haven’t ejected): `-- create-elm-app@2.0.3

Then, specify:

1. Operating system: Windows 10  (1803)
2. Browser and version (if relevant):

### Steps to Reproduce

1. elm-app test --watch

### Actual Behavior

Watching for changes...
Error: listen EADDRINUSE \\.\pipe\elm_test-7164
    at Server.setupListenHandle [as _listen2] (net.js:1343:19)
    at listenInCluster (net.js:1401:12)
    at Server.listen (net.js:1496:5)
    at C:\Users\andre\AppData\Roaming\npm\node_modules\create-elm-app\node_modules\elm-test\lib\supervisor.js:257:12
    at new Promise (<anonymous>)
    at Object.run (C:\Users\andre\AppData\Roaming\npm\node_modules\create-elm-app\node_modules\elm-test\lib\supervisor.js:20:10)
    at C:\Users\andre\AppData\Roaming\npm\node_modules\create-elm-app\node_modules\elm-test\lib\elm-test.js:176:25
    at <anonymous>
Unhandled exception while running the tests: { Error: write EPIPE
    at Socket._writeGeneric (net.js:768:25)
    at Socket._write (net.js:787:8)
    at doWrite (_stream_writable.js:396:12)
    at writeOrBuffer (_stream_writable.js:382:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:711:40)
    at Server.initWorker (C:\Users\andre\AppData\Roaming\npm\node_modules\create-elm-app\node_modules\elm-test\lib\supervisor.js:203:14)
    at emitOne (events.js:116:13)
    at Server.emit (events.js:211:7)
    at Pipe.onconnection (net.js:1570:8) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }

**Comment by halfzebra** [comment] 2018-11-05 22:54
Hi @mandrolic!

Sorry for a late reply, it doesn't look like the problem is caused by Create Elm App itself https://github.com/rtfeldman/node-test-runner/pull/309

The fix will be released as soon as the bug is fixed in `node-test-runner`.

I'm closing this issue, please feel free to reopen it if you find it necessary.

**Closed by halfzebra** 2018-11-05 22:54 UTC
