### ISSUE TITLE
Subdirectories

### ISSUE THREAD

**Issue by jtrunick** [halfzebra/create-elm-app#205] opened 2017-11-12 06:17 UTC
The readme indicates I can put Elm files in subdirectories under src/ but that doesn't work for live reloading, I tried adding the subdirectory to source-directories but that didn't help either.

**Comment by halfzebra** [comment] 2017-11-13 10:26
Hello @jtrunick! Thanks for reporting this issue.

Unfortunately, we can not help you without having additional information about the OS, Create Elm App and Node version you are running.

Please provide us with the information about your environment by running these commands in terminal:

1. `node -v`: 
2. `npm -v`:
3. `yarn --version` (if you use Yarn):
4. `npm ls create-elm-app -g` (if you haven’t ejected): 

Then, specify:

1. Operating system:
2. Browser and version (if relevant):

**Comment by galkowskit** [comment] 2017-11-14 19:27
Yeah, I seem to have the same problem. The thing is - the hot reload (and compilation) works only if I save the Main.elm file (or possibly other files in the `/src` folder) but it won't be triggered at all if I edit and save files in eg. `/src/core/Router.elm`. To have it recompile I have to save `Main.elm` regardless where the changes were done. So I think it must be something with how the watchers for file changes are set up.

node: 8.4.0
npm: 5.3.0
yarn: 1.0.1

`create-react-app` installed today, works like this before and after ejecting.

**Comment by halfzebra** [comment] 2017-11-14 20:06
@galkowskit what OS are you running?

**Comment by galkowskit** [comment] 2017-11-14 20:53
@halfzebra macOS Sierra 10.12.6.

**Comment by jenyckee** [comment] 2017-11-23 13:00
Same here, only Main.elm will trigger changes

**Comment by IngeniousPentaSquid** [comment] 2017-11-27 03:03
Can confirm, MacOS High Sierra (10.3), same issue.

**Comment by IngeniousPentaSquid** [comment] 2017-11-27 04:13
Hello all,

For everyone having this issue after digging around changing "watchOptions" in webpackDevServer.config.js fixes the issue: (Note you have to have run elm-app eject for you to access this and then run the app using npm start)

        watchOptions: {
            ignored: /node_modules/,
            aggregateTimeout: 300,
            poll: 1000
        },

The added options are aggregateTimeout and poll..

**Comment by galkowskit** [comment] 2017-11-27 09:20
Awesome, I'll try this workaround once I'm back home after work. Maybe the creators would accept it as a PR if it turns out to be working?

**Comment by littleStudent** [comment] 2017-11-27 10:14
Hmm I am not having this issue. (macOS 10.13)
Would `aggregateTimeout` not slow down the recompile? Sounds more like a workaround.

**Comment by halfzebra** [comment] 2017-11-27 13:13
@IngeniousPentaSquid thanks for the info, can you please confirm that you are experiencing this issue with the latest version of Create Elm App?

@galkowskit It looks like the only difference is that Webpack will ignore `/node_modules/`, the rest is the same as [default values,](https://webpack.js.org/configuration/watch/) so it's unclear whether the issue is with the loader or Webpack itself.

**Comment by IngeniousPentaSquid** [comment] 2017-11-27 13:16
@halfzebra Latest version of create elm app. Works fine on my Windows environment without said changes.

**Comment by halfzebra** [comment] 2017-12-30 14:59
This is supposed to be fixed in the latest releases.

I'm closing this issue, please feel free to reopen it if it's necessary.

**Closed by halfzebra** 2017-12-30 14:59 UTC
Labels: fix

**Comment by jgoodall628** [comment] 2019-11-27 20:26
Same issue.
node 12.13.1
yarn 1.19.2
create-elm-app 4.1.1
npm 6.12.1
