### ISSUE TITLE
Outdated dependencies (npm)

### ISSUE THREAD

**Issue by wscherphof** [halfzebra/create-elm-app#354] opened 2019-05-13 21:51 UTC
`npm install create-elm-app -g` renders:
```
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
npm WARN deprecated fsevents@1.2.4: Way too old
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
npm WARN deprecated sw-precache@5.2.1: Please migrate to Workbox: https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-sw
npm WARN deprecated sw-toolbox@3.6.0: Please migrate to Workbox: https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-sw
```
Things do still work, but I wonder how long. Any dependencies that are expected to be problematic upgrades?

**Comment by tennety** [comment] 2019-05-28 21:14
These dependencies (specifically `fsevents`) are causing a failure while installing on node `v12.3.1`. Downgrading to `v10.15.3` works.

**Comment by halfzebra** [comment] 2019-05-30 15:18
Hello, thank you for reporting this issue!

I have looked into it and it seems like the issue is originating in [rtfeldman/node-test-runner](https://github.com/rtfeldman/node-test-runner)

There is a PR addressing this issue, so, for now, I will not be able to provide Node v12 support. 😕 
https://github.com/rtfeldman/node-test-runner/pull/361

**Comment by wscherphof** [comment] 2019-06-13 21:22
The rtfeldman/node-test-runner#361 issue has been resolved now.

**Comment by dimlksin2** [comment] 2019-08-02 06:57
export ADBLOCK=1 && npm i

**Comment by halfzebra** [comment] 2020-03-23 14:21
Hello friends,

Thanks for your attention to this issue! 👍 
I have added a Renovate Bot to speed-up the update procedure from now on.

I'm closing this issue, let me know if you have further comments on this.

**Closed by halfzebra** 2020-03-23 14:21 UTC
