### ISSUE TITLE
Make Warnings visible, even when `elm-app start` successfully compiles

### ISSUE THREAD

**Issue by undreren** [halfzebra/create-elm-app#15] opened 2016-09-23 17:38 UTC
When `elm-app start` fails to compile, you'll get a list of warnings and errors, but when it succeeds, the warnings does not show.

It would be helpful to show the warnings along with the "compiled successfully" screen, as they often contain some useful information.

**Comment by jackfranklin** [comment] 2016-11-07 13:06
@halfzebra if you have not started work on this I'd love to take a stab at it? :)

**Comment by halfzebra** [comment] 2016-11-07 15:08
@jackfranklin That would be awesome!

As of today #36, #38 are in my pipeline for the next release.

**Comment by jackfranklin** [comment] 2016-11-19 12:14
@halfzebra so I took a look at this and I think there might be a bug in the elm-webpack-loader. It doesn't ever seem to pass the warnings through - so in the script where we call `stats.hasWarnings()`, it's always `false`, and the warnings is an empty array, even when there were warnings logged to the console.

**Comment by jdashton** [comment] 2017-07-31 18:55
I wonder if there's a different approach that would avoid the need for the hasWarnings call. Specifically, if you use a non-destructive screen clear, instead of totally wiping the screen buffer, then users would have the option of scrolling up to go back and see the results of the compilation, including any warnings or other informational messages.

**Comment by halfzebra** [comment] 2017-07-31 19:28
@jdashton the thing is that [node-elm-compiler](https://github.com/rtfeldman/node-elm-compiler) will only print out warnings, when there's a compilation error. There's no way of retrieving the warnings without changing the way node compiler works.

**Comment by jdashton** [comment] 2017-07-31 21:15
My confusion would be that I _think_ that I see warnings scroll past in that window, even in the no-error case. However, the web server clears the window in a way that prevents scrolling back to check what I have just seen. I apologize if I'm misinterpreting what I'm seeing.

**Comment by andys8** [comment] 2017-08-09 19:39
@halfzebra If it's missing in the `node-elm-compiler`, we should request this feature. Here is the where the flag is passed: https://github.com/rtfeldman/node-elm-compiler/blob/d1a27f4ccc4537a243725875f511af285c209e61/index.js#L174

If @jdashton is right, it would be because of the `react-dev-utils::clearConsole()`, right? I didn't verify it, but I certainly have it in mind like he describes it.

**Comment by galkowskit** [comment] 2017-11-14 19:34
Yeah, I can confirm that I can see what @jdashton is describing. I have a simple application where this is happening (both before and after ejecting). Here is a short video, even though the browser popped out I managed to catch before it got cleared. You can pause at 0:06 to see it clearly.

https://monosnap.com/file/uEgcw5Pb7gln7VknabN5gHRy4ROG3Y#

**Comment by dcecile** [comment] 2018-02-13 11:18
I'm just getting started with Elm (using the Webpack setup from _Create Elm App_), and I can't figure out a good way to see warnings for all the Elm files in my project.

- Using `elm-app start` I only get a flash of warning text (i.e. this issue here)
- Using `elm-app make --warn` has the side effect of generating an `index.html` file (not needed for a Webpack build), and it seems to have some caching features which [interfere](https://github.com/elm-lang/elm-make/issues/27) with a full report
- From what I see, there's no way to configure warnings as errors [yet](https://github.com/elm-lang/elm-make/issues/108)

Any suggested workarounds for now?

**Comment by dcecile** [comment] 2018-02-15 01:56
(FWIW, this is the crude script that I'm currently using as a workaround) 👇

`rm -rf elm-stuff/build-artifacts/0.18.0/MYPROJECT && elm-make src/Main.elm --warn --output /dev/null`

**Comment by halfzebra** [comment] 2018-02-20 11:23
The problem with this issue is that the loader does not send the warnings in the way intended by the Webpack's API. The warnings are piped into stdout directly from the compiler.

There are two options:
- Change the way the node distribution of compiler sends the warnings and pass them to the loader
  Related to [rtfeldman/node-elm-compiler/issues/66](https://github.com/rtfeldman/node-elm-compiler/issues/66)
- Revisit the logic, that clears out the stdout in Create Elm App

I'll see what I can do with the second option for now 🤔

**Comment by halfzebra** [comment] 2018-08-06 20:49
Closing this due to https://github.com/elm-community/elm-webpack-loader/issues/141#issuecomment-406651493

**Closed by halfzebra** 2018-08-06 20:49 UTC
Labels: wontfix
