### ISSUE TITLE
elm-app test -> Cannot find module 'Tuple' from Lazy.List import

### ISSUE THREAD

**Issue by jimmack1963** [halfzebra/create-elm-app#72] opened 2016-12-03 05:20 UTC
So, I am trying Elm first time, everything is latest version as of today.  I even thought to do npm install of elm-test -g.  I am on Win 10 (sorry) node 6.9.1, have not made any changes after cloning from git.

> C:\elm\app1>elm-app test
> I cannot find module 'Tuple'.
> 
> Module 'Lazy.List' is trying to import it.
> 
> Potential problems could be:
>   * Misspelled the module name
>   * Need to add a source directory or new dependency to elm-package.json
> Compilation failed for Main.elm

Thanks for making this; sorry I don't know enough to fix it myself

**Comment by halfzebra** [comment] 2016-12-03 13:19
@jimmack1963 Hello and thank you for reporting an issue!

It looks like you are using slightly outdated version. Please, make sure, that you are running the latest version of Create Elm App.
```
npm install create-elm-app -g  # Will install the latest version.
```

The simplest way would be to create a new application and copy the code you have written into it.

You don't need to install `elm-test`, since it's already with Create Elm App already.

**Comment by jimmack1963** [comment] 2016-12-03 16:51
Hi, thanks for the suggestion.  Tried 8:07am pacific. No change.  Sequence of commands, copy/pasted from command line:

npm install create-elm-app -g
create-elm-app testingWorks
cd testingWorks
elm-app test

> I cannot find module 'Tuple'.
> 
> Module 'Lazy.List' is trying to import it.
> 
> Potential problems could be:
>   * Misspelled the module name
>   * Need to add a source directory or new dependency to elm-package.json
> Compilation failed for Main.elm

-----------------------------------------------------------------------------------------
Windows 10.
node 6.9.1
I am using the command prompt.

**Comment by halfzebra** [comment] 2016-12-03 17:08
@jimmack1963 can you please run the command and tell me what output you get?
```
create-elm-app
```

**Comment by eezis** [comment] 2016-12-11 19:34
The problem here seems to be with lazy-list, I believe the old package was named 'elm-lazy-list'. Here's what I did to get the tests to run ... 

eae:words~$ **cd tests**
eae:tests~$ **elm package install elm-community/lazy-list**
To install elm-community/lazy-list I would like to add the following
dependency to elm-package.json:

    "elm-community/lazy-list": "1.0.0 <= v < 2.0.0"

May I add that to elm-package.json for you? [Y/n] **y**

Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-community/lazy-list 1.0.0
  Upgrade:
    elm-community/elm-test (2.1.0 => 3.1.0)
    elm-community/json-extra (1.1.0 => 2.0.0)
    elm-community/shrink (1.1.0 => 2.0.0)
    elm-lang/core (4.0.5 => 5.0.0)
    elm-lang/html (1.1.0 => 2.0.0)
    elm-lang/lazy (1.0.0 => 2.0.0)
    elm-lang/virtual-dom (1.1.1 => 2.0.2)
    mgold/elm-random-pcg (3.0.4 => 4.0.2)
    rtfeldman/node-test-runner (2.0.1 => 3.0.0)
  Remove:
    elm-community/elm-lazy-list

Do you approve of this plan? [Y/n] **y**
Starting downloads...

  ● elm-community/json-extra 2.0.0
  ● elm-community/shrink 2.0.0
  ● elm-community/lazy-list 1.0.0
  ● elm-community/elm-test 3.1.0
  ● elm-lang/lazy 2.0.0
  ● elm-lang/core 5.0.0
  ● elm-lang/html 2.0.0
  ● elm-lang/virtual-dom 2.0.2
  ● mgold/elm-random-pcg 4.0.2
  ● rtfeldman/node-test-runner 3.0.0

Packages configured successfully!
eae:tests~$ **cd ..**


Now the tests run as expected (3 passed, 1 failed -- I believe it was designed to fail).

====

tests/elm-packages.json gets updated

    "dependencies": {
        "elm-community/elm-test": "3.0.0 <= v < 4.0.0",
        **"elm-community/lazy-list": "1.0.0 <= v < 2.0.0",**

**Comment by jackfranklin** [comment] 2016-12-20 09:47
@halfzebra I just hit this too.  I'm running create-elm-app 0.2.1 and elm 0.18.0.

To fix, I did:

```
cd tests
elm package install -y
(lots of stuff to be installed here)
```

And then everything runs as expected. Is `elm package install` not being run on the `tests` folder properly or something?

**Comment by jackfranklin** [comment] 2016-12-20 09:49
I think the solution here might be to have an explicit install step that does `cd tests && elm package install -y` too. @halfzebra would you accept a PR that did that?

**Comment by Rolograaf** [comment] 2016-12-28 17:15
When I run `elm-app test` -- from the very first time I got it running -- it gave compiler error. Can somebody advise what is wrong?
```
-- TYPE MISMATCH ------------------------------------------------- .\.\Tests.elm

The argument to function `first` is causing a mismatch.

14|                               Tuple.first App.init
                                              ^^^^^^^^
Function `first` is expecting the argument to be:

    ( App.Model, Cmd App.Msg )

But it is:

    String -> ( App.Model, Cmd App.Msg )
```

**Comment by halfzebra** [comment] 2017-05-01 23:57
Closing this in favor of #120

**Closed by halfzebra** 2017-05-01 23:57 UTC
Labels: fix
