### ISSUE TITLE
Example uses /logo.svg which isn't working with a different PUBLIC_URL

### ISSUE THREAD

**Issue by perty** [halfzebra/create-elm-app#227] opened 2018-02-01 12:14 UTC
### Is this a bug report?

yes

### Environment

1. `node -v`: 
2. `npm -v`:
3. `yarn --version` (if you use Yarn):
4. `npm ls create-elm-app -g` (if you haven’t ejected): 

Then, specify:

1. Operating system:
2. Browser and version (if relevant):

### Steps to Reproduce

(Write your steps here:)

1. 
2. 
3. 

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Please add screenshots!)

### Reproducible Demo

(Paste the link to an example project and exact instructions to reproduce the issue.)

I changed the file Main.elm reference from "/logo.svg" to "logo.svg". It now works with a different PUBLIC_URL than /.

**Comment by halfzebra** [comment] 2018-02-05 10:36
@perty Thanks for reporting this issue!

This looks like an expected behavior to me, `PUBLIC_PATH` was added to support the option of adding static assets outside the module system(this is exactly what happens to the logo file here).

Please check out the docs about [Adding Assets Outside of the Module System](https://github.com/halfzebra/create-elm-app/blob/master/template/README.md#adding-assets-outside-of-the-module-system), I hope this clarifies the intended way of using `PUBLIC_PATH`.

I'm going to close this issue for now, but please feel free to re-open it if you have further questions.

**Closed by halfzebra** 2018-02-05 10:36 UTC
