### ISSUE TITLE
Making Configuration Possible

### ISSUE THREAD

**Issue by leifg** [halfzebra/create-elm-app#178] opened 2017-09-19 21:05 UTC
I know create-elm-app is a zero configuration tool. But I have some variables I want to replace on the build process (more specifically the endpoint url to my API).

Is there something in this tool that helps me out here? Something like

```shell
API_ENDPOINT=https://my-awesome-api elm-app build
```

**Comment by bekapod** [comment] 2017-09-21 17:56
I'm not a maintainer of this project, but you can create a .env file or a .env.local file in your project root and you should then be able to access vars declared in there. create-elm-app (and create-react-app) will only inject env variables if you have `ELM_APP_` (or `REACT_APP_` for the react version) prefix. See config/env.js for more details if needed!

I'm still new to Elm myself but this link should help you with accessing the env variables in your app (in case you aren't already aware): https://robots.thoughtbot.com/configuring-an-elm-app-with-environment-variables-via-webpack#passing-config-to-elm-as-flags

**Comment by halfzebra** [comment] 2017-09-28 17:00
@leifg passing variables by setting them from the terminal or by using `ELM_APP_` prefix will work only for the JavaScript part as @bekapod says.

I'm considering adding variable substitution inside of Elm code, so it's possible to pass stringified values into Elm, without using [Html.programWithFlags](http://package.elm-lang.org/packages/elm-lang/html/2.0.0/Html#programWithFlags)

Example:

```sh
$ ELM_APP_API_URL= https://api.github.com elm-app build
```

```elm
apiUrl : String
apiUrl =
    "%ELM_APP_API_URL%"

-- Is transformed into:
apiUrl : String
apiUrl =
    "https://api.github.com"
```

@jackfranklin @fobos @gyzerok How does that sound?

**Comment by gyzerok** [comment] 2017-09-28 18:18
Hi folks!

Being able to change things like API url is essential during development. As you all know it's quite often nowadays to have as a separate thing. Definitely agree with necessity of being able to use API which do not live next to the frontend.

Can proxying solve described problem? For example all requests to `/api/foo` gets proxied to `api.github.com/foo`. As far as I know this feature do already exist.

I'd compare idea of introducing variable substitution with unintended side-effects. This is due to the fact that you can effectively put such code in whatever place in your project and then due to some refactoring end up with unintended behaviour.

Also future release of Elm will introduce some concept of environment which might be useful for this case specifically. So I'd rather wait to see how it will look.

**Comment by halfzebra** [comment] 2017-09-28 19:34
@gyzerok Thanks for the insight! :+1: 

> Can proxying solve described problem?

Not if the `apiUrl` is at another domain.

I'm going to wait with the token substitution.

**Comment by jackfranklin** [comment] 2017-09-29 08:13
I'd be +1 on that config change @halfzebra. I've had to swap in API tokens into Elm and it's always been way harder than it would be in JS. I think the Webpack string-replace-loader would do that for us maybe?

Maybe we make people define them in a `.elm-env` or similar so it's clear where they are coming from?

I agree with @gyzerok that the substitution does let people shoot themselves in the foot but I think we should document it clearly and be clear what it is and isn't suitable for.

**Comment by leifg** [comment] 2017-10-01 21:54
@bekapod's approach worked like a charme. Thanks for that! I documented the process in a [blog post](http://blog.leif.io/configure-your-elm-app-with-env-variables/) for everyone who is interested.

**Comment by splodingsocks** [comment] 2017-11-17 23:32
@halfzebra I like that approach (the string substitution approach, and I think it makes sense)

**Comment by joshhornby** [comment] 2018-01-02 14:20
Any news regarding https://github.com/halfzebra/create-elm-app/issues/178#issuecomment-332899609 I don't really like passing these strings in via flags. String substitution would be great

**Comment by halfzebra** [comment] 2018-07-03 16:59
Closing this issue for now.

String substitution was introduced some time ago [Using custom environment variables.](https://github.com/halfzebra/create-elm-app/blob/master/template/README.md#using-custom-environment-variables)

Please feel free to reopen the issue if necessary! 🙂

**Closed by halfzebra** 2018-07-03 16:59 UTC
Labels: question
