### ISSUE TITLE
Installation fails with newer node versions

### ISSUE THREAD

**Issue by oaalto** [halfzebra/create-elm-app#218] opened 2017-12-24 08:53 UTC
### Environment

1. `node -v`:  v8.6.0
2. `npm -v`: v5.3.0

Then, specify:

1. Operating system: Windows 10

### Steps to Reproduce

1. npm i -g create-elm-app 

### Expected Behavior

The installation would complete successfully.

### Actual Behavior
Log:

2373 verbose stack Error: Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"8.6.0","npm":"5.3.0"})
2373 verbose stack     at checkEngine (C:\Users\ollia\AppData\Roaming\nvm\v8.6.0\node_modules\npm\node_modules\npm-install-checks\index.js:13:14)
2373 verbose stack     at module.exports.isInstallable (C:\Users\ollia\AppData\Roaming\nvm\v8.6.0\node_modules\npm\lib\install\validate-args.js:49:3)
2373 verbose stack     at resolveWithNewModule (C:\Users\ollia\AppData\Roaming\nvm\v8.6.0\node_modules\npm\lib\install\deps.js:590:10)
2373 verbose stack     at C:\Users\ollia\AppData\Roaming\nvm\v8.6.0\node_modules\npm\lib\install\deps.js:536:7
2373 verbose stack     at C:\Users\ollia\AppData\Roaming\nvm\v8.6.0\node_modules\npm\node_modules\iferr\index.js:13:50
2373 verbose stack     at C:\Users\ollia\AppData\Roaming\nvm\v8.6.0\node_modules\npm\node_modules\call-limit\call-limit.js:22:12
2373 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:131:7)
2373 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
2374 verbose pkgid got@5.7.1
2376 verbose Windows_NT 10.0.16299
2377 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "-g" "create-elm-app"
2378 verbose node v8.6.0
2379 verbose npm  v5.3.0
2380 error code ENOTSUP
2381 error notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"8.6.0","npm":"5.3.0"})
2382 error notsup Not compatible with your version of node/npm: got@5.7.1
2383 error notsup Not compatible with your version of node/npm: got@5.7.1
2383 error notsup Required: {"node":">=0.10.0 <7"}
2383 error notsup Actual:   {"npm":"5.3.0","node":"8.6.0"}

**Comment by halfzebra** [comment] 2017-12-29 13:43
@oaalto thanks for reporting this issue!

It might be related to #212, I'll try to fix this during the next few days.

**Comment by halfzebra** [comment] 2018-02-05 10:38
It seems like this issue has been fixed with the latest patch releases.

I'm closing this, for now. 

Please feel free to re-open the issue if you are still experiencing the problem.

**Comment by oaalto** [comment] 2018-02-13 08:43
Still failing to install. Tried git bash, command prompt and powershell. Now it's complaining about a different package.

npm i -g create-elm-app
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for upath@1.0.0: wanted: {"node":">=0.10 <=7"} (current: {"node":"8.9.4","npm":"5.6.0"})
npm ERR! notsup Not compatible with your version of node/npm: upath@1.0.0
npm ERR! notsup Not compatible with your version of node/npm: upath@1.0.0
npm ERR! notsup Required: {"node":">=0.10 <=7"}
npm ERR! notsup Actual:   {"npm":"5.6.0","node":"8.9.4"}

**Comment by oaalto** [comment] 2018-02-14 10:09
Using yarn seems to work. So that's a usable workaround.

The eject command fails with the same error as above, though.

**Comment by halfzebra** [comment] 2018-02-14 20:57
@oaalto my best bet is that this issue is caused by the local npm cache on your machine.

Please try running `npm cache clear --force` and installing again, I don't think this issue is Windows-specific.

I will close this issue, please leave a comment if clearing the cache doesn't help.

**Closed by halfzebra** 2018-02-14 20:57 UTC
Labels: fix
